Repository UwUClub/AwARea, pull requests merged in 2024-01, with the labels that each got.

#30 Aw 46 fix google sign in on iOS
  flutter_area/ios/Podfile.lock
  flutter_area/ios/Runner.xcodeproj/project.pbxproj
  flutter_area/ios/Runner.xcworkspace/contents.xcworkspacedata
  flutter_area/ios/Runner/Info.plist
  flutter_area/lib/Core/Manager/user_manager.dart
  flutter_area/lib/Utils/constants.dart
Labels: enhancement

#33 Aw 40 front mobile home
  flutter_area/lib/UI/Home/home_mobile_view.dart
  flutter_area/lib/UI/Home/home_view.dart
  flutter_area/lib/UI/MainNavigator/main_navigator.dart
  flutter_area/lib/UI/MainNavigator/main_navigator_mobile.dart
  flutter_area/lib/UI/NewTask/Components/action_card.dart
  flutter_area/lib/UI/NewTask/Components/action_selection.dart
  flutter_area/lib/UI/NewTask/Components/reaction_card.dart
  flutter_area/lib/UI/NewTask/Components/reaction_selection.dart
  flutter_area/lib/UI/NewTask/Components/task_card.dart
  flutter_area/lib/UI/NewTask/action_selection.dart
  flutter_area/lib/UI/NewTask/new_task_mobile_view.dart
  flutter_area/lib/UI/NewTask/new_task_view.dart
  flutter_area/lib/Utils/Extensions/double_extensions.dart
  flutter_area/lib/main.dart
Labels: enhancement

#34 Aw 36 connexions page
  flutter_area/Dockerfile
  flutter_area/lib/Core/Manager/user_manager.dart
  flutter_area/lib/UI/Connections/connections_mobile_view.dart
  flutter_area/lib/UI/Connections/connections_view.dart
  flutter_area/lib/UI/MainNavigator/main_navigator_mobile.dart
  flutter_area/lib/UI/Settings/settings_mobile_view.dart
  flutter_area/lib/UI/Settings/settings_view.dart
  flutter_area/lib/l10n/app_en.arb
  flutter_area/lib/l10n/app_es.arb
  flutter_area/lib/l10n/app_fr.arb
Labels: enhancement

#36 Add: generic action-reaction creation
  api/src/action-reaction/_utils/pipes/get-action-reaction.pipe.ts
  api/src/action-reaction/action-reaction.controller.ts
  api/src/action-reaction/action-reaction.repository.ts
  api/src/action-reaction/action-reaction.schema.ts
  api/src/action-reaction/action-reaction.service.ts
  api/src/actions/_utils/dto/request/create-action.dto.ts
  api/src/actions/actions.controller.ts
  api/src/actions/actions.module.ts
  api/src/actions/actions.repository.ts
  api/src/actions/actions.service.ts
  api/src/actions/schemas/actions.schema.ts
  api/src/app.module.ts
  api/src/auth/auth.service.ts
  api/src/google-api/google-api.controller.ts
  api/src/google-api/google-api.service.ts
  api/src/nasa/nasa.service.ts
  api/src/reactions/_utils/dto/request/create-reaction.dto.ts
  api/src/reactions/reaction.repository.ts
  api/src/reactions/reactions.controller.ts
  api/src/reactions/reactions.module.ts
  api/src/reactions/reactions.service.ts
  api/src/reactions/schemas/create-draft.schema.ts
  api/src/reactions/schemas/reactions.schema.ts
  api/src/task.service.ts
  api/src/users/users.schema.ts
  api/src/weather/weather.service.ts
  docker-compose.yml
Labels: enhancement

#39 Add download APK button
  flutter_area/lib/UI/Home/home_view.dart
  flutter_area/lib/l10n/app_en.arb
  flutter_area/lib/l10n/app_es.arb
  flutter_area/lib/l10n/app_fr.arb
Labels: enhancement

#40 Aw 42 documentation tests cicd
  .github/workflows/back.yml
  .github/workflows/front.yml
  api/test/test.sh
  doc/developer/Front.md
  doc/user/HowToMakeSlackApp.md
  flutter_area/devtools_options.yaml
  flutter_area/lib/main.dart
  package-lock.json
  package.json
  pnpm-lock.yaml
Labels: documentation, tests

#44 Add Github actions on front
  flutter_area/lib/Core/Manager/action_reaction_manager.dart
  flutter_area/lib/UI/NewTask/Components/action_card.dart
  flutter_area/lib/UI/NewTask/Components/action_form.dart
  flutter_area/lib/UI/NewTask/Components/action_selection.dart
  flutter_area/lib/UI/NewTask/Components/reaction_card.dart
  flutter_area/lib/UI/NewTask/Components/reaction_selection.dart
  flutter_area/lib/UI/NewTask/Components/task_card.dart
  flutter_area/lib/UI/NewTask/new_task_mobile_view.dart
  flutter_area/lib/UI/NewTask/new_task_view.dart
  flutter_area/lib/l10n/app_en.arb
  flutter_area/lib/l10n/app_es.arb
  flutter_area/lib/l10n/app_fr.arb
Labels: enhancement

#45 Updated doc
  README.md
  doc/developer/.env.example
  doc/developer/Introduction.md
  doc/developer/end/Back-end.md
  doc/developer/end/Front-end.md
Labels: documentation

#48 AW-54 slack reactions front
  flutter_area/lib/Core/Manager/action_reaction_manager.dart
  flutter_area/lib/UI/NewTask/Components/action_card.dart
  flutter_area/lib/UI/NewTask/Components/action_selection.dart
  flutter_area/lib/UI/NewTask/Components/reaction_card.dart
  flutter_area/lib/UI/NewTask/Components/reaction_form.dart
  flutter_area/lib/UI/NewTask/new_task_mobile_view.dart
  flutter_area/lib/UI/NewTask/new_task_view.dart
Labels: enhancement

#55 Fix user response in login / google-auth
  api/src/auth/_utils/dto/response/succes-login.dto.ts
  api/src/auth/auth.service.ts
  flutter_area/lib/Core/Manager/google_manager.dart
  flutter_area/lib/Core/Manager/user_manager.dart
  flutter_area/lib/UI/Boostrap/boostrap_view.dart
Labels: bug

#56 Fix front notifiers
  flutter_area/lib/Core/Manager/action_reaction_manager.dart
  flutter_area/lib/Core/Manager/github_manager.dart
  flutter_area/lib/Core/Manager/google_manager.dart
  flutter_area/lib/Core/Manager/user_manager.dart
  flutter_area/lib/UI/Callback/callback_github.dart
  flutter_area/lib/UI/Connections/connections_mobile_view.dart
  flutter_area/lib/UI/Connections/connections_view.dart
  flutter_area/lib/UI/Connections/connections_viewmodel.dart
  flutter_area/lib/UI/NewTask/new_task_mobile_view.dart
  flutter_area/lib/UI/NewTask/new_task_view.dart
  flutter_area/lib/UI/NewTask/new_task_viewmodel.dart
Labels: bug

#59 Add google connection
  flutter_area/lib/Core/Manager/google_manager.dart
  flutter_area/lib/UI/Connections/connections_view.dart
  flutter_area/lib/UI/Login/google_button.dart
  flutter_area/lib/UI/Profile/profile_view.dart
Labels: enhancement

#60 Dev
  api/src/auth/auth.controller.ts
  flutter_area/lib/Core/Manager/google_manager.dart
  flutter_area/lib/UI/Connections/connections_view.dart
  flutter_area/lib/UI/Login/google_button.dart
  flutter_area/lib/UI/Profile/profile_view.dart
Labels: enhancement

#63 Dev
  flutter_area/lib/UI/Connections/connections_mobile_view.dart
  flutter_area/lib/UI/MainNavigator/main_navigator_mobile.dart
  flutter_area/lib/UI/NewTask/Components/action_form.dart
  flutter_area/lib/UI/NewTask/Components/reaction_form.dart
  flutter_area/lib/UI/NewTask/new_task_view.dart
  flutter_area/lib/UI/Profile/profile_mobile_view.dart
  flutter_area/lib/l10n/app_ar.arb
  flutter_area/lib/l10n/app_de.arb
  flutter_area/lib/l10n/app_en.arb
  flutter_area/lib/l10n/app_es.arb
  flutter_area/lib/l10n/app_it.arb
  flutter_area/lib/l10n/app_ko.arb
  flutter_area/lib/l10n/app_pl.arb
  flutter_area/lib/l10n/app_pt.arb
  flutter_area/lib/l10n/app_ru.arb
  flutter_area/lib/l10n/app_sv.arb
  flutter_area/lib/l10n/app_zh.arb
Labels: enhancement
